language: node_js
sudo: true
dist: trusty
node_js:
- '4'
- '6'
install:
- yarn
before_script:
  - |

       $(npm bin)/set-up-ssh --key "$encrypted_994c1a696aaf_key" \
                             --iv "$encrypted_994c1a696aaf_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
notifications:
  email:
    on_failure: change
    on_success: change
after_success:
- npm run coveralls
